### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by dittaeva** [lordsutch/osm-makeroads#1]
I wanted to try this script, but have given up because the R dependencies fail to install because of failing dependencies. This on the latest Ubuntu. It could possibly help if some of them could be installed from standard debian/ubuntu repositiories instead of through CRAN, since most seem to fail because of external dependencies. So some more hints of what needs to be installed, would be helpful.

"Filename to process" in process.R could need some elaboration. If traces are fetched from osm, then why do you need to supply a file? What is the role of the file, just for a bounding box, or will traces in the file be processed too? Before trying, I thought I'd have to supply the trace files myself.

**Comment by lordsutch** [comment]
Sorry it took nearly 6 years to get back to you on this. Ugh.

The installation instructions have been updated; hopefully they fix the issues you note.

If you supply a filename, the code will use the GPX file that's provided. If you set it to NULL, it will download the GPS traces from OpenStreetMap from the appropriate boundary box. I would generally recommend just downloading the region you are going to test once and using that file as the input, which avoids hammering the OpenStreetMap server by downloading the same area over and over.
